name: "register"
mode: "dev"
port: 8080
version: "0.0.1"
start-time: "2021-10-24"
machine: 1

mysql:
  host: "127.0.0.1"
  user: "root"
  port : 3306
  password: "557320"
  Database: "register"
  maxopen: 100
  maxfree: 50

log:
  filename: "daily.log"
  level: "info"
  max_size: 5
  max_age: 30
  max_backups: 5


